// Operator-editable agent policy + workflow catalog.
// Thresholds / prompts here drive guardrail / router / grounding / gate / draft
// plus TypeSafe cookbook enhancements (bands, dates, cascade, hazard, etc.).

export type PolicyPresetId =
  | "balanced"
  | "strict"
  | "lenient"
  | "exam_ready"
  | "custom";

export type AgentId =
  | "guardrail"
  | "triage"
  | "router"
  | "draft"
  | "grounding"
  | "confidence"
  | "gate"
  | "hazard"
  | "playbook"
  | "dedupe";

export type ConsoleSettings = {
  orgName: string;
  exportTitlePrefix: string;
  exportFooter: string;
  memoSections: string;
};

export type AgentConfig = {
  version: number;
  updatedAt: string | null;
  preset: PolicyPresetId | "custom";
  console: ConsoleSettings;
  guardrail: {
    enabled: boolean;
    label: string;
    description: string;
    injectionBlockThreshold: number;
  };
  triage: {
    enabled: boolean;
    label: string;
    description: string;
    escalateFullPathThreshold: number;
    fastPathMinConfidence: number;
    escalateConfidenceCeiling: number;
    /** Mid-range noul band → uncertain. */
    noulUncertainLow: number;
    noulUncertainHigh: number;
    /** Choice confidence below this → uncertain band. */
    choiceMinConfidence: number;
    /** Prefer coarse parent when fine category confidence below this. */
    coarseTaxonomyCutoff: number;
    /** Run Domain→Framework→Topic beam classify. */
    beamClassifyEnabled: boolean;
  };
  router: {
    enabled: boolean;
    label: string;
    description: string;
    routineCategories: string[];
    /** Prefer coarse taxonomy label for routine routing when level=coarse. */
    preferCoarseForRouting: boolean;
  };
  draft: {
    enabled: boolean;
    label: string;
    description: string;
    obligationSystemPrompt: string;
    memoSystemPrompt: string;
    /** Azure small → TypeSafe verify → Azure big cascade. */
    sdeCascadeEnabled: boolean;
    /** Escalate when any field-wrongness noul ≥ this. */
    sdeFireThreshold: number;
    /** Typed due-date extraction after obligation extract. */
    dueDateExtractEnabled: boolean;
    dueDateReviewBelow: number;
    /** Force gate human confirm when any due date needs_review. */
    dueDateForceConfirm: boolean;
  };
  grounding: {
    enabled: boolean;
    label: string;
    description: string;
    supportThreshold: number;
    inventedThreshold: number;
    /** Citation Choice auto-accept confidence. */
    citationAutoAccept: number;
  };
  confidence: {
    enabled: boolean;
    label: string;
    description: string;
    /** Editable composite weights (renormalized). */
    weightGrounded: number;
    weightComplete: number;
    weightActionable: number;
    weightOverall: number;
  };
  gate: {
    enabled: boolean;
    label: string;
    description: string;
    autoApproveAbove: number;
    humanConfirmAbove: number;
    /** Force pending_review when any triage/gate band is uncertain. */
    forceConfirmOnUncertain: boolean;
  };
  hazard: {
    enabled: boolean;
    label: string;
    description: string;
    blockSeverityAbove: number;
    reviewSeverityAbove: number;
    hazardNoulBlock: number;
  };
  playbook: {
    enabled: boolean;
    label: string;
    description: string;
    coveredThreshold: number;
  };
  dedupe: {
    enabled: boolean;
    label: string;
    description: string;
  };
};

const DEFAULT_OBLIGATION_PROMPT =
  "You are a regulatory compliance analyst at a bank. Extract every concrete obligation, " +
  "required action, or deadline from the document. Respond with JSON only: " +
  '{"obligations": [{"owner": string (role, e.g. \'BSA Officer\'; use \'Unassigned\' if unclear), ' +
  '"action": string, "due_date": string (exact date if stated, else "unspecified"), ' +
  '"source_quote": string (short verbatim quote supporting it)}]}. ' +
  "Do not invent dates, owners, or obligations not supported by the text. If none, return {\"obligations\": []}.";

const DEFAULT_MEMO_PROMPT =
  "You are a regulatory compliance officer drafting an internal memo. Write a professional memo in Markdown " +
  "with exactly these sections: {{MEMO_SECTIONS}}. " +
  "Be factual and concise. Never invent dates, regulation citations, or obligations not supported by the source text. " +
  "Mark anything uncertain as an open question.";

export const DEFAULT_AGENT_CONFIG: AgentConfig = {
  version: 1,
  updatedAt: null,
  preset: "balanced",
  console: {
    orgName: "RegPilot",
    exportTitlePrefix: "RegPilot examiner package",
    exportFooter:
      "Generated by RegPilot. All samples and redactions follow the console's fictional-demo policy.",
    memoSections:
      "## Subject\n## Background\n## Key obligations\n## Recommended actions\n## Open questions",
  },
  guardrail: {
    enabled: true,
    label: "Guardrail agent",
    description:
      "Regex PII redaction first, then TypeSafe injection noul. Blocked inputs never reach Azure.",
    injectionBlockThreshold: 0.55,
  },
  triage: {
    enabled: true,
    label: "Triage agent (System One)",
    description:
      "TypeSafe Choice + Noul judgments for category, urgency, jurisdiction, escalate, uncertainty bands, coarse taxonomy, beam.",
    escalateFullPathThreshold: 0.75,
    fastPathMinConfidence: 0.8,
    escalateConfidenceCeiling: 0.85,
    noulUncertainLow: 0.3,
    noulUncertainHigh: 0.7,
    choiceMinConfidence: 0.55,
    coarseTaxonomyCutoff: 0.7,
    beamClassifyEnabled: true,
  },
  router: {
    enabled: true,
    label: "Router",
    description:
      "Rules over triage + escalate noul. Critical / escalate → full Azure; high-conf routine → fast path.",
    routineCategories: ["Consumer Compliance", "Other", "Operational Risk"],
    preferCoarseForRouting: true,
  },
  draft: {
    enabled: true,
    label: "Draft agent (Azure)",
    description:
      "Azure OpenAI extracts obligations (optional SDE cascade) and drafts the memo. Typed due-date extract via TypeSafe.",
    obligationSystemPrompt: DEFAULT_OBLIGATION_PROMPT,
    memoSystemPrompt: DEFAULT_MEMO_PROMPT,
    sdeCascadeEnabled: true,
    sdeFireThreshold: 0.7,
    dueDateExtractEnabled: true,
    dueDateReviewBelow: 0.6,
    dueDateForceConfirm: true,
  },
  grounding: {
    enabled: true,
    label: "Grounding agent (System One)",
    description:
      "Citation-grade locate + Choice (supports/contradicts/says_nothing/fabricated). Soft-fails cap confidence.",
    supportThreshold: 0.55,
    inventedThreshold: 0.55,
    citationAutoAccept: 0.8,
  },
  confidence: {
    enabled: true,
    label: "Confidence agent (System One)",
    description:
      "Composite of grounded / complete / actionable nouls plus overall score. Weights editable; recompute without re-inference.",
    weightGrounded: 0.25,
    weightComplete: 0.25,
    weightActionable: 0.25,
    weightOverall: 0.25,
  },
  gate: {
    enabled: true,
    label: "Confidence gate",
    description:
      "Deterministic thresholds: auto-approve, human confirm, or needs-work. Uncertain bands force confirm.",
    autoApproveAbove: 0.9,
    humanConfirmAbove: 0.5,
    forceConfirmOnUncertain: true,
  },
  hazard: {
    enabled: true,
    label: "Outbound hazard screen",
    description:
      "After memo draft: hazard nouls + harm severity → pass / review / block before gate.",
    blockSeverityAbove: 3.2,
    reviewSeverityAbove: 1.8,
    hazardNoulBlock: 0.7,
  },
  playbook: {
    enabled: true,
    label: "Playbook coverage",
    description:
      "Batched TypeSafe Noul/Score per playbook checklist step; soft-suggest missing steps.",
    coveredThreshold: 0.55,
  },
  dedupe: {
    enabled: true,
    label: "Obligation dedupe",
    description:
      "Score alignment (same/related/different) + field nouls for Review curator merges.",
  },
};

export type WorkflowStep = {
  id: AgentId | "intake" | "human" | "export" | "eval";
  title: string;
  role: string;
  implementation: string;
  apis: string[];
  runtime: "typesafe" | "azure" | "rules" | "human" | "ui";
  agentKey?: keyof Omit<
    AgentConfig,
    "version" | "updatedAt" | "preset" | "console"
  >;
};

/** Catalog used by the Workflow page — mirrors real code paths. */
export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: "intake",
    title: "Intake",
    role: "Operator pastes / uploads / loads a fictional sample.",
    implementation: "app/intake/page.tsx · POST /api/triage | /api/pipeline",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "ui",
  },
  {
    id: "guardrail",
    title: "Guardrail",
    role: "PII redaction + injection screen before any drafting model runs.",
    implementation: "lib/redact.ts · lib/jev.ts#jevGuardrail · lib/typesafe.ts#typesafeTriage",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "guardrail",
  },
  {
    id: "triage",
    title: "Triage",
    role: "Typed category / urgency / jurisdiction + escalate noul + uncertainty bands + coarse/beam.",
    implementation: "lib/jev.ts#jevClassify · lib/typesafe.ts#typesafeTriage",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "triage",
  },
  {
    id: "router",
    title: "Router",
    role: "Fast path (small Azure) vs full analysis (gpt-5.4).",
    implementation: "lib/jev.ts#routeDecision",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "rules",
    agentKey: "router",
  },
  {
    id: "draft",
    title: "Draft",
    role: "Obligation extraction (SDE cascade) + due dates + memo generation.",
    implementation: "lib/jev.ts#extractObligationsCascade · lib/jev.ts#draftMemo",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "azure",
    agentKey: "draft",
  },
  {
    id: "dedupe",
    title: "Obligation dedupe",
    role: "Alignment score + field nouls for curator merges.",
    implementation: "lib/typesafe.ts#typesafeDedupeObligations",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "dedupe",
  },
  {
    id: "grounding",
    title: "Grounding",
    role: "Citation-grade check of obligations and memo vs source.",
    implementation: "lib/typesafe.ts#typesafeGroundObligations",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "grounding",
  },
  {
    id: "playbook",
    title: "Playbook coverage",
    role: "Coverage vector over framework checklist steps.",
    implementation: "lib/typesafe.ts#typesafePlaybookCoverage",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "playbook",
  },
  {
    id: "hazard",
    title: "Hazard screen",
    role: "Outbound memo hazard nouls + severity before gate.",
    implementation: "lib/typesafe.ts#typesafeMemoHazard",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "hazard",
  },
  {
    id: "confidence",
    title: "Confidence",
    role: "System One quality score with editable weights; may be soft-capped.",
    implementation: "lib/jev.ts#jevConfidence · lib/typesafe.ts#typesafeConfidence",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "confidence",
  },
  {
    id: "gate",
    title: "Gate",
    role: "Auto-approve, pending review, or needs-work (uncertain bands force confirm).",
    implementation: "lib/jev.ts#gateDecision",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "rules",
    agentKey: "gate",
  },
  {
    id: "human",
    title: "Human review",
    role: "Approve, request changes, re-analyze, filter uncertain, merge duplicates.",
    implementation: "app/review/page.tsx · app/items/[id]/page.tsx · POST /api/review",
    apis: ["GET/POST /api/review", "GET /api/detail"],
    runtime: "human",
  },
  {
    id: "export",
    title: "Examiner export",
    role: "Downloadable markdown/JSON package with audit + grounding + coverage.",
    implementation: "lib/export.ts · GET /api/export · /items/[id]",
    apis: ["GET /api/export", "GET /api/detail"],
    runtime: "ui",
  },
  {
    id: "eval",
    title: "Calibration / eval",
    role: "Replay samples; report precision@band; suggest thresholds. No production write.",
    implementation: "app/api/eval/route.ts · Settings",
    apis: ["POST /api/eval", "GET /api/eval"],
    runtime: "typesafe",
  },
];

function clamp01(n: number, fallback: number): number {
  if (typeof n !== "number" || Number.isNaN(n)) return fallback;
  return Math.min(1, Math.max(0, n));
}

function clip(s: unknown, max: number, fallback: string): string {
  const v = typeof s === "string" ? s : fallback;
  return v.slice(0, max) || fallback;
}

function mergeAgentBlock<T extends Record<string, unknown>>(
  base: T,
  patch: Partial<T> | undefined,
  numericKeys: (keyof T)[]
): T {
  if (!patch) return base;
  const next = { ...base, ...patch } as T;
  for (const k of numericKeys) {
    const fallback = base[k] as number;
    const raw = patch[k];
    if (typeof raw === "number") {
      (next as Record<string, unknown>)[k as string] = clamp01(raw, fallback);
    } else if (raw === undefined) {
      (next as Record<string, unknown>)[k as string] = fallback;
    }
  }
  const p = patch as Record<string, unknown>;
  const b = base as Record<string, unknown>;
  const n = next as Record<string, unknown>;
  if ("enabled" in b) {
    n.enabled = p.enabled !== false;
  }
  if ("label" in b) {
    n.label = clip(p.label, 80, String(b.label));
  }
  if ("description" in b) {
    n.description = clip(p.description, 500, String(b.description));
  }
  return next;
}

export function normalizeAgentConfig(raw: unknown): AgentConfig {
  const base = structuredClone(DEFAULT_AGENT_CONFIG);
  if (!raw || typeof raw !== "object") return base;
  const r = raw as Partial<AgentConfig>;

  if (r.console) {
    base.console = {
      orgName: clip(r.console.orgName, 80, base.console.orgName),
      exportTitlePrefix: clip(
        r.console.exportTitlePrefix,
        120,
        base.console.exportTitlePrefix
      ),
      exportFooter: clip(r.console.exportFooter, 500, base.console.exportFooter),
      memoSections: clip(
        r.console.memoSections,
        800,
        base.console.memoSections
      ),
    };
  }

  if (
    r.preset === "balanced" ||
    r.preset === "strict" ||
    r.preset === "lenient" ||
    r.preset === "exam_ready" ||
    r.preset === "custom"
  ) {
    base.preset = r.preset;
  }

  base.guardrail = mergeAgentBlock(base.guardrail, r.guardrail, [
    "injectionBlockThreshold",
  ]);
  base.triage = {
    ...mergeAgentBlock(base.triage, r.triage, [
      "escalateFullPathThreshold",
      "fastPathMinConfidence",
      "escalateConfidenceCeiling",
      "noulUncertainLow",
      "noulUncertainHigh",
      "choiceMinConfidence",
      "coarseTaxonomyCutoff",
    ]),
    beamClassifyEnabled: r.triage?.beamClassifyEnabled !== false,
  };
  if (r.router) {
    const cats = Array.isArray(r.router.routineCategories)
      ? r.router.routineCategories.map(String).slice(0, 12)
      : base.router.routineCategories;
    base.router = {
      ...base.router,
      ...r.router,
      routineCategories: cats.length ? cats : base.router.routineCategories,
      enabled: r.router.enabled !== false,
      preferCoarseForRouting: r.router.preferCoarseForRouting !== false,
      label: clip(r.router.label, 80, base.router.label),
      description: clip(r.router.description, 500, base.router.description),
    };
  }
  if (r.draft) {
    base.draft = {
      ...base.draft,
      enabled: r.draft.enabled !== false,
      label: clip(r.draft.label, 80, base.draft.label),
      description: clip(r.draft.description, 500, base.draft.description),
      obligationSystemPrompt: clip(
        r.draft.obligationSystemPrompt,
        4000,
        base.draft.obligationSystemPrompt
      ),
      memoSystemPrompt: clip(
        r.draft.memoSystemPrompt,
        4000,
        base.draft.memoSystemPrompt
      ),
      sdeCascadeEnabled: r.draft.sdeCascadeEnabled !== false,
      sdeFireThreshold: clamp01(
        r.draft.sdeFireThreshold ?? base.draft.sdeFireThreshold,
        base.draft.sdeFireThreshold
      ),
      dueDateExtractEnabled: r.draft.dueDateExtractEnabled !== false,
      dueDateReviewBelow: clamp01(
        r.draft.dueDateReviewBelow ?? base.draft.dueDateReviewBelow,
        base.draft.dueDateReviewBelow
      ),
      dueDateForceConfirm: r.draft.dueDateForceConfirm !== false,
    };
  }
  base.grounding = mergeAgentBlock(base.grounding, r.grounding, [
    "supportThreshold",
    "inventedThreshold",
    "citationAutoAccept",
  ]);
  base.confidence = mergeAgentBlock(base.confidence, r.confidence, [
    "weightGrounded",
    "weightComplete",
    "weightActionable",
    "weightOverall",
  ]);
  base.gate = {
    ...mergeAgentBlock(base.gate, r.gate, [
      "autoApproveAbove",
      "humanConfirmAbove",
    ]),
    forceConfirmOnUncertain: r.gate?.forceConfirmOnUncertain !== false,
  };
  base.hazard = mergeAgentBlock(base.hazard, r.hazard, [
    "blockSeverityAbove",
    "reviewSeverityAbove",
    "hazardNoulBlock",
  ]);
  // severity score is 0..4 — clamp specially
  if (r.hazard) {
    const bs = r.hazard.blockSeverityAbove;
    const rs = r.hazard.reviewSeverityAbove;
    if (typeof bs === "number" && !Number.isNaN(bs)) {
      base.hazard.blockSeverityAbove = Math.min(4, Math.max(0, bs));
    }
    if (typeof rs === "number" && !Number.isNaN(rs)) {
      base.hazard.reviewSeverityAbove = Math.min(4, Math.max(0, rs));
    }
  }
  base.playbook = mergeAgentBlock(base.playbook, r.playbook, [
    "coveredThreshold",
  ]);
  if (r.dedupe) {
    base.dedupe = {
      ...base.dedupe,
      enabled: r.dedupe.enabled !== false,
      label: clip(r.dedupe.label, 80, base.dedupe.label),
      description: clip(r.dedupe.description, 500, base.dedupe.description),
    };
  }

  base.version = typeof r.version === "number" ? r.version : base.version;
  base.updatedAt = typeof r.updatedAt === "string" ? r.updatedAt : base.updatedAt;
  return base;
}

export function resolveMemoSystemPrompt(cfg: AgentConfig): string {
  const sections =
    cfg.console.memoSections.trim() ||
    DEFAULT_AGENT_CONFIG.console.memoSections;
  return (cfg.draft.memoSystemPrompt || DEFAULT_MEMO_PROMPT).replace(
    /\{\{MEMO_SECTIONS\}\}/g,
    sections.replace(/\n/g, ", ")
  );
}

/** Renormalize confidence weights and blend raw judgments into a score. */
export function compositeConfidenceScore(opts: {
  grounded: number;
  complete: number;
  actionable: number;
  overall01: number;
  weights: {
    weightGrounded: number;
    weightComplete: number;
    weightActionable: number;
    weightOverall: number;
  };
}): number {
  const w = opts.weights;
  const sum =
    w.weightGrounded +
    w.weightComplete +
    w.weightActionable +
    w.weightOverall;
  const norm = sum > 0 ? sum : 1;
  const score =
    (w.weightGrounded / norm) * opts.grounded +
    (w.weightComplete / norm) * opts.complete +
    (w.weightActionable / norm) * opts.actionable +
    (w.weightOverall / norm) * opts.overall01;
  return Math.min(1, Math.max(0, score));
}
