// Operator-editable agent policy + workflow catalog.
// Thresholds / prompts here drive guardrail / router / grounding / gate / draft.

export type PolicyPresetId =
  | "balanced"
  | "strict"
  | "lenient"
  | "exam_ready"
  | "custom";

export type AgentId =
  | "guardrail"
  | "triage"
  | "router"
  | "draft"
  | "grounding"
  | "confidence"
  | "gate";

export type ConsoleSettings = {
  orgName: string;
  exportTitlePrefix: string;
  exportFooter: string;
  memoSections: string;
};

export type AgentConfig = {
  version: number;
  updatedAt: string | null;
  preset: PolicyPresetId | "custom";
  console: ConsoleSettings;
  guardrail: {
    enabled: boolean;
    label: string;
    description: string;
    injectionBlockThreshold: number;
  };
  triage: {
    enabled: boolean;
    label: string;
    description: string;
    escalateFullPathThreshold: number;
    fastPathMinConfidence: number;
    escalateConfidenceCeiling: number;
  };
  router: {
    enabled: boolean;
    label: string;
    description: string;
    routineCategories: string[];
  };
  draft: {
    enabled: boolean;
    label: string;
    description: string;
    obligationSystemPrompt: string;
    memoSystemPrompt: string;
  };
  grounding: {
    enabled: boolean;
    label: string;
    description: string;
    supportThreshold: number;
    inventedThreshold: number;
  };
  confidence: {
    enabled: boolean;
    label: string;
    description: string;
  };
  gate: {
    enabled: boolean;
    label: string;
    description: string;
    autoApproveAbove: number;
    humanConfirmAbove: number;
  };
};

const DEFAULT_OBLIGATION_PROMPT =
  "You are a regulatory compliance analyst at a bank. Extract every concrete obligation, " +
  "required action, or deadline from the document. Respond with JSON only: " +
  '{"obligations": [{"owner": string (role, e.g. \'BSA Officer\'; use \'Unassigned\' if unclear), ' +
  '"action": string, "due_date": string (exact date if stated, else "unspecified"), ' +
  '"source_quote": string (short verbatim quote supporting it)}]}. ' +
  "Do not invent dates, owners, or obligations not supported by the text. If none, return {\"obligations\": []}.";

const DEFAULT_MEMO_PROMPT =
  "You are a regulatory compliance officer drafting an internal memo. Write a professional memo in Markdown " +
  "with exactly these sections: {{MEMO_SECTIONS}}. " +
  "Be factual and concise. Never invent dates, regulation citations, or obligations not supported by the source text. " +
  "Mark anything uncertain as an open question.";

export const DEFAULT_AGENT_CONFIG: AgentConfig = {
  version: 1,
  updatedAt: null,
  preset: "balanced",
  console: {
    orgName: "RegPilot",
    exportTitlePrefix: "RegPilot examiner package",
    exportFooter:
      "Generated by RegPilot. All samples and redactions follow the console's fictional-demo policy.",
    memoSections:
      "## Subject\n## Background\n## Key obligations\n## Recommended actions\n## Open questions",
  },
  guardrail: {
    enabled: true,
    label: "Guardrail agent",
    description:
      "Regex PII redaction first, then TypeSafe injection noul. Blocked inputs never reach Azure.",
    injectionBlockThreshold: 0.55,
  },
  triage: {
    enabled: true,
    label: "Triage agent (System One)",
    description:
      "TypeSafe Choice + Noul judgments for category, urgency, jurisdiction, and escalate.",
    escalateFullPathThreshold: 0.75,
    fastPathMinConfidence: 0.8,
    escalateConfidenceCeiling: 0.85,
  },
  router: {
    enabled: true,
    label: "Router",
    description:
      "Rules over triage + escalate noul. Critical / escalate → full Azure; high-conf routine → fast path.",
    routineCategories: ["Consumer Compliance", "Other", "Operational Risk"],
  },
  draft: {
    enabled: true,
    label: "Draft agent (Azure)",
    description:
      "Azure OpenAI extracts obligations (JSON) and drafts the regulatory memo. System One does not generate prose.",
    obligationSystemPrompt: DEFAULT_OBLIGATION_PROMPT,
    memoSystemPrompt: DEFAULT_MEMO_PROMPT,
  },
  grounding: {
    enabled: true,
    label: "Grounding agent (System One)",
    description:
      "TypeSafe Nouls check each obligation and the memo against the redacted source. Soft-fails cap confidence.",
    supportThreshold: 0.55,
    inventedThreshold: 0.55,
  },
  confidence: {
    enabled: true,
    label: "Confidence agent (System One)",
    description:
      "Composite of grounded / complete / actionable nouls plus an overall quality score.",
  },
  gate: {
    enabled: true,
    label: "Confidence gate",
    description:
      "Deterministic thresholds: auto-approve, human confirm, or needs-work before export.",
    autoApproveAbove: 0.9,
    humanConfirmAbove: 0.5,
  },
};

export type WorkflowStep = {
  id: AgentId | "intake" | "human" | "export";
  title: string;
  role: string;
  implementation: string;
  apis: string[];
  runtime: "typesafe" | "azure" | "rules" | "human" | "ui";
  agentKey?: keyof Omit<
    AgentConfig,
    "version" | "updatedAt" | "preset" | "console"
  >;
};

/** Catalog used by the Workflow page — mirrors real code paths. */
export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: "intake",
    title: "Intake",
    role: "Operator pastes / uploads / loads a fictional sample.",
    implementation: "app/intake/page.tsx · POST /api/triage | /api/pipeline",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "ui",
  },
  {
    id: "guardrail",
    title: "Guardrail",
    role: "PII redaction + injection screen before any drafting model runs.",
    implementation: "lib/redact.ts · lib/jev.ts#jevGuardrail · lib/typesafe.ts#typesafeTriage",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "guardrail",
  },
  {
    id: "triage",
    title: "Triage",
    role: "Typed category / urgency / jurisdiction + escalate noul.",
    implementation: "lib/jev.ts#jevClassify · lib/typesafe.ts#typesafeTriage",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "triage",
  },
  {
    id: "router",
    title: "Router",
    role: "Fast path (small Azure) vs full analysis (gpt-5.4).",
    implementation: "lib/jev.ts#routeDecision",
    apis: ["POST /api/triage", "POST /api/pipeline"],
    runtime: "rules",
    agentKey: "router",
  },
  {
    id: "draft",
    title: "Draft",
    role: "Obligation extraction + memo generation on Azure OpenAI.",
    implementation: "lib/jev.ts#extractObligations · lib/jev.ts#draftMemo · lib/azure.ts",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "azure",
    agentKey: "draft",
  },
  {
    id: "grounding",
    title: "Grounding",
    role: "Citation-style check of obligations and memo vs source.",
    implementation: "lib/typesafe.ts#typesafeGroundObligations",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "grounding",
  },
  {
    id: "confidence",
    title: "Confidence",
    role: "System One quality score with reasons; may be soft-capped by grounding.",
    implementation: "lib/jev.ts#jevConfidence · lib/typesafe.ts#typesafeConfidence",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "typesafe",
    agentKey: "confidence",
  },
  {
    id: "gate",
    title: "Gate",
    role: "Auto-approve, pending review, or needs-work.",
    implementation: "lib/jev.ts#gateDecision",
    apis: ["POST /api/analyze", "POST /api/pipeline"],
    runtime: "rules",
    agentKey: "gate",
  },
  {
    id: "human",
    title: "Human review",
    role: "Approve, request changes, re-analyze, or bulk-clear the queue.",
    implementation: "app/review/page.tsx · app/items/[id]/page.tsx · POST /api/review",
    apis: ["GET/POST /api/review", "GET /api/detail"],
    runtime: "human",
  },
  {
    id: "export",
    title: "Examiner export",
    role: "Downloadable markdown/JSON package with audit + grounding.",
    implementation: "lib/export.ts · GET /api/export · /items/[id]",
    apis: ["GET /api/export", "GET /api/detail"],
    runtime: "ui",
  },
];

function clamp01(n: number, fallback: number): number {
  if (typeof n !== "number" || Number.isNaN(n)) return fallback;
  return Math.min(1, Math.max(0, n));
}

function clip(s: unknown, max: number, fallback: string): string {
  const v = typeof s === "string" ? s : fallback;
  return v.slice(0, max) || fallback;
}

export function normalizeAgentConfig(raw: unknown): AgentConfig {
  const base = structuredClone(DEFAULT_AGENT_CONFIG);
  if (!raw || typeof raw !== "object") return base;
  const r = raw as Partial<AgentConfig>;

  if (r.console) {
    base.console = {
      orgName: clip(r.console.orgName, 80, base.console.orgName),
      exportTitlePrefix: clip(
        r.console.exportTitlePrefix,
        120,
        base.console.exportTitlePrefix
      ),
      exportFooter: clip(r.console.exportFooter, 500, base.console.exportFooter),
      memoSections: clip(
        r.console.memoSections,
        800,
        base.console.memoSections
      ),
    };
  }

  if (
    r.preset === "balanced" ||
    r.preset === "strict" ||
    r.preset === "lenient" ||
    r.preset === "exam_ready" ||
    r.preset === "custom"
  ) {
    base.preset = r.preset;
  }

  if (r.guardrail) {
    base.guardrail = {
      ...base.guardrail,
      ...r.guardrail,
      injectionBlockThreshold: clamp01(
        r.guardrail.injectionBlockThreshold ??
          base.guardrail.injectionBlockThreshold,
        base.guardrail.injectionBlockThreshold
      ),
      enabled: r.guardrail.enabled !== false,
      label: clip(r.guardrail.label, 80, base.guardrail.label),
      description: clip(r.guardrail.description, 500, base.guardrail.description),
    };
  }
  if (r.triage) {
    base.triage = {
      ...base.triage,
      ...r.triage,
      escalateFullPathThreshold: clamp01(
        r.triage.escalateFullPathThreshold ??
          base.triage.escalateFullPathThreshold,
        base.triage.escalateFullPathThreshold
      ),
      fastPathMinConfidence: clamp01(
        r.triage.fastPathMinConfidence ?? base.triage.fastPathMinConfidence,
        base.triage.fastPathMinConfidence
      ),
      escalateConfidenceCeiling: clamp01(
        r.triage.escalateConfidenceCeiling ??
          base.triage.escalateConfidenceCeiling,
        base.triage.escalateConfidenceCeiling
      ),
      enabled: r.triage.enabled !== false,
      label: clip(r.triage.label, 80, base.triage.label),
      description: clip(r.triage.description, 500, base.triage.description),
    };
  }
  if (r.router) {
    const cats = Array.isArray(r.router.routineCategories)
      ? r.router.routineCategories.map(String).slice(0, 12)
      : base.router.routineCategories;
    base.router = {
      ...base.router,
      ...r.router,
      routineCategories: cats.length ? cats : base.router.routineCategories,
      enabled: r.router.enabled !== false,
      label: clip(r.router.label, 80, base.router.label),
      description: clip(r.router.description, 500, base.router.description),
    };
  }
  if (r.draft) {
    base.draft = {
      ...base.draft,
      enabled: r.draft.enabled !== false,
      label: clip(r.draft.label, 80, base.draft.label),
      description: clip(r.draft.description, 500, base.draft.description),
      obligationSystemPrompt: clip(
        r.draft.obligationSystemPrompt,
        4000,
        base.draft.obligationSystemPrompt
      ),
      memoSystemPrompt: clip(
        r.draft.memoSystemPrompt,
        4000,
        base.draft.memoSystemPrompt
      ),
    };
  }
  if (r.grounding) {
    base.grounding = {
      ...base.grounding,
      ...r.grounding,
      supportThreshold: clamp01(
        r.grounding.supportThreshold ?? base.grounding.supportThreshold,
        base.grounding.supportThreshold
      ),
      inventedThreshold: clamp01(
        r.grounding.inventedThreshold ?? base.grounding.inventedThreshold,
        base.grounding.inventedThreshold
      ),
      enabled: r.grounding.enabled !== false,
      label: clip(r.grounding.label, 80, base.grounding.label),
      description: clip(r.grounding.description, 500, base.grounding.description),
    };
  }
  if (r.confidence) {
    base.confidence = {
      ...base.confidence,
      enabled: r.confidence.enabled !== false,
      label: clip(r.confidence.label, 80, base.confidence.label),
      description: clip(
        r.confidence.description,
        500,
        base.confidence.description
      ),
    };
  }
  if (r.gate) {
    base.gate = {
      ...base.gate,
      ...r.gate,
      autoApproveAbove: clamp01(
        r.gate.autoApproveAbove ?? base.gate.autoApproveAbove,
        base.gate.autoApproveAbove
      ),
      humanConfirmAbove: clamp01(
        r.gate.humanConfirmAbove ?? base.gate.humanConfirmAbove,
        base.gate.humanConfirmAbove
      ),
      enabled: r.gate.enabled !== false,
      label: clip(r.gate.label, 80, base.gate.label),
      description: clip(r.gate.description, 500, base.gate.description),
    };
  }

  base.version = typeof r.version === "number" ? r.version : base.version;
  base.updatedAt = typeof r.updatedAt === "string" ? r.updatedAt : base.updatedAt;
  return base;
}

export function resolveMemoSystemPrompt(cfg: AgentConfig): string {
  const sections =
    cfg.console.memoSections.trim() ||
    DEFAULT_AGENT_CONFIG.console.memoSections;
  return (cfg.draft.memoSystemPrompt || DEFAULT_MEMO_PROMPT).replace(
    /\{\{MEMO_SECTIONS\}\}/g,
    sections.replace(/\n/g, ", ")
  );
}
