// Examiner export package — memo + obligations + triage + audit in one artifact.

export type ExportItem = {
  id: number;
  title: string;
  category: string | null;
  urgency: string | null;
  jurisdiction: string | null;
  confidence: number | null;
  fast_path: boolean;
  status: string;
  source_text_redacted: string;
  created_at: string;
};

export type ExportObligation = {
  owner: string;
  action: string;
  due_date: string;
  source_quote: string;
};

export type ExportAudit = {
  actor: string;
  action: string;
  detail: string | null;
  created_at: string;
};

export type ExportPackage = {
  exportedAt: string;
  item: ExportItem;
  obligations: ExportObligation[];
  memo: string;
  modelUsed: string;
  audit: ExportAudit[];
  grounding: {
    model?: string;
    overallSupported?: number;
    inventedClaims?: number;
    unsupportedCount?: number;
    softFail?: boolean;
    details?: string;
  } | null;
};

export function buildExportMarkdown(
  pkg: ExportPackage,
  opts?: { titlePrefix?: string; footer?: string; orgName?: string }
): string {
  const { item, obligations, memo, modelUsed, audit, grounding } = pkg;
  const prefix = opts?.titlePrefix || "RegPilot examiner package";
  const org = opts?.orgName || "RegPilot";
  const footer =
    opts?.footer ||
    "Generated by RegPilot. All samples and redactions follow the console's fictional-demo policy.";
  const lines: string[] = [
    `# ${prefix} — #${item.id}`,
    ``,
    `Organization: ${org}`,
    `Exported: ${pkg.exportedAt}`,
    ``,
    `## Matter`,
    ``,
    `- **Title:** ${item.title}`,
    `- **Status:** ${item.status}`,
    `- **Category:** ${item.category || "—"}`,
    `- **Urgency:** ${item.urgency || "—"}`,
    `- **Jurisdiction:** ${item.jurisdiction || "—"}`,
    `- **Confidence:** ${item.confidence != null ? item.confidence.toFixed(2) : "—"}`,
    `- **Path:** ${item.fast_path ? "fast" : "full"}`,
    `- **Created:** ${item.created_at}`,
    ``,
    `## Obligations`,
    ``,
  ];

  if (!obligations.length) {
    lines.push("_No obligations extracted._", ``);
  } else {
    for (const [i, o] of obligations.entries()) {
      lines.push(
        `### ${i + 1}. ${o.owner}`,
        ``,
        `- **Action:** ${o.action}`,
        `- **Due:** ${o.due_date}`,
        `- **Source:** “${o.source_quote}”`,
        ``
      );
    }
  }

  lines.push(`## Draft memo`, ``, `_Drafted by ${modelUsed || "unknown"}_`, ``, memo || "_No memo._", ``);

  if (grounding) {
    lines.push(
      `## Grounding check (TypeSafe)`,
      ``,
      `- **Model:** ${grounding.model || "—"}`,
      `- **Overall supported noul:** ${
        grounding.overallSupported != null
          ? grounding.overallSupported.toFixed(2)
          : "—"
      }`,
      `- **Unsupported obligations:** ${grounding.unsupportedCount ?? "—"}`,
      `- **Invented claims noul:** ${
        grounding.inventedClaims != null
          ? grounding.inventedClaims.toFixed(2)
          : "—"
      }`,
      `- **Soft-fail:** ${grounding.softFail ? "yes" : "no"}`,
      grounding.details ? `- **Detail:** ${grounding.details}` : "",
      ``
    );
  }

  lines.push(`## Source (redacted)`, ``, "```", item.source_text_redacted, "```", ``);
  lines.push(`## Audit trail`, ``);
  if (!audit.length) {
    lines.push("_No audit entries._", ``);
  } else {
    for (const a of audit) {
      lines.push(
        `- \`${a.created_at}\` · **${a.actor}** · \`${a.action}\`${
          a.detail ? ` — ${a.detail}` : ""
        }`
      );
    }
    lines.push(``);
  }

  lines.push(`---`, `_${footer}_`, ``);
  return lines.filter((l) => l !== undefined).join("\n");
}
