// Examiner export package — memo + obligations + triage + audit in one artifact.

import type { ItemJudgments } from "./provenance";

export type ExportItem = {
  id: number;
  title: string;
  category: string | null;
  urgency: string | null;
  jurisdiction: string | null;
  confidence: number | null;
  fast_path: boolean;
  status: string;
  source_text_redacted: string;
  created_at: string;
  policy_version?: number | null;
  preset?: string | null;
};

export type ExportObligation = {
  owner: string;
  action: string;
  due_date: string;
  source_quote: string;
};

export type ExportAudit = {
  actor: string;
  action: string;
  detail: string | null;
  created_at: string;
};

export type ExportProvenance = {
  policy_version: number | null;
  preset: string | null;
  judgments: ItemJudgments | null;
};

export type ExportPackage = {
  exportedAt: string;
  item: ExportItem;
  obligations: ExportObligation[];
  memo: string;
  modelUsed: string;
  audit: ExportAudit[];
  grounding: {
    model?: string;
    overallSupported?: number;
    inventedClaims?: number;
    unsupportedCount?: number;
    softFail?: boolean;
    details?: string;
  } | null;
  provenance?: ExportProvenance | null;
};

function fmtNoul(n: number | undefined | null): string {
  return n != null && Number.isFinite(n) ? n.toFixed(2) : "—";
}

export function buildExportMarkdown(
  pkg: ExportPackage,
  opts?: { titlePrefix?: string; footer?: string; orgName?: string }
): string {
  const { item, obligations, memo, modelUsed, audit, grounding, provenance } =
    pkg;
  const prefix = opts?.titlePrefix || "RegPilot examiner package";
  const org = opts?.orgName || "RegPilot";
  const footer =
    opts?.footer ||
    "Generated by RegPilot. All samples and redactions follow the console's fictional-demo policy.";
  const lines: string[] = [
    `# ${prefix} — #${item.id}`,
    ``,
    `Organization: ${org}`,
    `Exported: ${pkg.exportedAt}`,
    ``,
    `## Matter`,
    ``,
    `- **Title:** ${item.title}`,
    `- **Status:** ${item.status}`,
    `- **Category:** ${item.category || "—"}`,
    `- **Urgency:** ${item.urgency || "—"}`,
    `- **Jurisdiction:** ${item.jurisdiction || "—"}`,
    `- **Confidence:** ${item.confidence != null ? item.confidence.toFixed(2) : "—"}`,
    `- **Path:** ${item.fast_path ? "fast" : "full"}`,
    `- **Created:** ${item.created_at}`,
    ``,
  ];

  const policyVersion =
    provenance?.policy_version ?? item.policy_version ?? null;
  const preset = provenance?.preset ?? item.preset ?? null;
  const judgments = provenance?.judgments ?? null;

  if (policyVersion != null || preset || judgments) {
    lines.push(`## Policy + System One judgments`, ``);
    lines.push(`- **Preset:** ${preset || "—"}`);
    lines.push(
      `- **Policy version:** ${policyVersion != null ? `v${policyVersion}` : "—"}`
    );
    if (judgments?.triage) {
      const t = judgments.triage;
      lines.push(
        `- **Injection noul:** ${fmtNoul(t.injectionNoul)}`,
        `- **Escalate noul:** ${fmtNoul(t.escalateNoul)}`,
        `- **Category:** ${t.category?.choice || "—"} (conf ${fmtNoul(t.category?.confidence)})`,
        `- **Urgency:** ${t.urgency?.choice || "—"} (conf ${fmtNoul(t.urgency?.confidence)})`,
        `- **Jurisdiction:** ${t.jurisdiction?.choice || "—"} (conf ${fmtNoul(t.jurisdiction?.confidence)})`
      );
      if (t.model) lines.push(`- **Triage model:** ${t.model}`);
    }
    if (judgments?.confidence) {
      lines.push(
        `- **Confidence score:** ${fmtNoul(judgments.confidence.score)}`
      );
      if (judgments.confidence.reasons?.length) {
        lines.push(
          `- **Confidence reasons:** ${judgments.confidence.reasons.join("; ")}`
        );
      }
    }
    if (judgments?.grounding) {
      const g = judgments.grounding;
      lines.push(
        `- **Grounding overall supported:** ${fmtNoul(g.overallSupported)}`,
        `- **Invented claims noul:** ${fmtNoul(g.inventedClaims)}`,
        `- **Unsupported obligations:** ${g.unsupportedCount}`,
        `- **Grounding soft-fail:** ${g.softFail ? "yes" : "no"}`
      );
      if (g.obligations?.length) {
        lines.push(``, `### Per-obligation grounding`, ``);
        for (const o of g.obligations) {
          lines.push(
            `- **#${o.index + 1} ${o.owner}** — supported noul ${fmtNoul(o.supportedNoul)} (${o.supported ? "ok" : "weak"}): ${o.action}`
          );
        }
      }
    }
    lines.push(``);
  }

  lines.push(`## Obligations`, ``);

  if (!obligations.length) {
    lines.push("_No obligations extracted._", ``);
  } else {
    for (const [i, o] of obligations.entries()) {
      lines.push(
        `### ${i + 1}. ${o.owner}`,
        ``,
        `- **Action:** ${o.action}`,
        `- **Due:** ${o.due_date}`,
        `- **Source:** “${o.source_quote}”`,
        ``
      );
    }
  }

  lines.push(`## Draft memo`, ``, `_Drafted by ${modelUsed || "unknown"}_`, ``, memo || "_No memo._", ``);

  if (grounding) {
    lines.push(
      `## Grounding check (TypeSafe)`,
      ``,
      `- **Model:** ${grounding.model || "—"}`,
      `- **Overall supported noul:** ${
        grounding.overallSupported != null
          ? grounding.overallSupported.toFixed(2)
          : "—"
      }`,
      `- **Unsupported obligations:** ${grounding.unsupportedCount ?? "—"}`,
      `- **Invented claims noul:** ${
        grounding.inventedClaims != null
          ? grounding.inventedClaims.toFixed(2)
          : "—"
      }`,
      `- **Soft-fail:** ${grounding.softFail ? "yes" : "no"}`,
      grounding.details ? `- **Detail:** ${grounding.details}` : "",
      ``
    );
  }

  lines.push(`## Source (redacted)`, ``, "```", item.source_text_redacted, "```", ``);
  lines.push(`## Audit trail`, ``);
  if (!audit.length) {
    lines.push("_No audit entries._", ``);
  } else {
    for (const a of audit) {
      lines.push(
        `- \`${a.created_at}\` · **${a.actor}** · \`${a.action}\`${
          a.detail ? ` — ${a.detail}` : ""
        }`
      );
    }
    lines.push(``);
  }

  lines.push(`---`, `_${footer}_`, ``);
  return lines.filter((l) => l !== undefined).join("\n");
}
